motherduck_profile:
  outputs:
    dev:
      type: duckdb
      path: "md:{{ env_var('MOTHERDB') }}?motherduck_token={{ env_var('MOTHERDUCK_TOKEN') }}"
      extensions:
        - httpfs
        - parquet
        - spatial
      schema: naptan_analysis
  target: dev
